### ISSUE TITLE
ValueError: keep_snps indices out of bounds

### ISSUE THREAD

**Issue by llandsmeer** [JonJala/mama#31]
Three hours into the ldscore computation, we ran into the following error:

```
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

keep_snps indices out of bounds
Traceback (most recent call last):
  File "/hpc/dhl_ec/llandsmeer/_cac_ta/mama/legacy/mama_ldscore.py", line 641, in main_func
    mama_LD_scores = estimate_LD_score_MAMA(args)
  File "/hpc/dhl_ec/llandsmeer/_cac_ta/mama/legacy/mama_ldscore.py", line 514, in estimate_LD_score_MAMA
    lN_mat, lN_df, M, M_5_50 = multi_ldScoreVarBlocks(args, ances_ind, ances_flag, ances_n, snp_index, ind_index, array_file, array_obj, array_snps)
  File "/hpc/dhl_ec/llandsmeer/_cac_ta/mama/legacy/mama_ldscore.py", line 138, in multi_ldScoreVarBlocks
    geno_array = array_obj(array_file, n, array_snps, keep_snps=snplist, keep_indivs=indlist, mafMin=args.maf)
  File "/hpc/dhl_ec/llandsmeer/_cac_ta/mama/legacy/mama_ldcalc.py", line 340, in __init__
    keep_indivs=keep_indivs, mafMin=mafMin)
  File "/hpc/dhl_ec/llandsmeer/_cac_ta/mama/legacy/mama_ldcalc.py", line 179, in __init__
    raise ValueError('keep_snps indices out of bounds')
ValueError: keep_snps indices out of bounds
Analysis terminated from error at Sat Feb 25 18:07:13 2023
Total time elapsed: 3.0h:24.540000000000873s
Cross-ancestry LD score estimation complete. Time elapsed: 3.0h:43.181886434555054s
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
```

what does it mean?

**Comment by llandsmeer** [comment]
Solved: the problem was duplicated snp ids in our input bed file
